<?php

/**
 * @file Implement Federal Russia Tourism agency open data integration.
 */

use Drupal\rtod;
use Drupal\rtod\structure;

/**
 * Implements hook_rtod_structure_handlers().
 */
function rtod_rtod_structure_handlers() {
  $handlers = array(
    'StructureHandler20140904' => array(
      'className' => 'StructureHandler20140904',
      'handledStructures' => array(
        'http://opendata.russiatourism.ru/7708550300-ReestrRosturizm77B/structure-20140904.json',
        'http://opendata.russiatourism.ru/7708550300-ReestrRosturizm77B#structure-20140904',
        'http://opendata.russiatourism.ru/7708550300-ReestrRosturizm50B/structure-20140904.json',
        'http://opendata.russiatourism.ru/7708550300-ReestrRosturizm50B#structure-20140904',
      ),
    ),
  );

  return $handlers;
}

/**
 * Implements hook_menu()
 */
function rtod_menu() {
  $items['admin/config/system/rtod'] = array(
    'title' => 'Russia Tourizm integration',
    'description' => 'Russia Tourizm integration related settings',
    'page callback' => 'rtod_admin_info_page',
    'access arguments' => array('administer rtod integration'),
    'file' => 'rtod.admin.inc',
  );
  $items['admin/config/system/rtod/info'] = array(
    'title' => t('Info'),
    'description' => 'Russia Tourizm integration info',
    'access arguments' => array('administer rtod integration'),
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'file' => 'rtod.admin.inc',
    'weight' => 1,
  );
  $items['admin/config/system/rtod/settings'] = array(
    'title' => 'Settings',
    'description' => 'Russia Tourizm integration configuration',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('rtod_settings_form'),
    'access arguments' => array('administer rtod integration'),
    'type' => MENU_LOCAL_TASK,
    'file' => 'rtod.admin.inc',
    'weight' => 2,
  );

  return $items;
}

/**
 * Implements hook_permission()
 */
function rtod_permission() {
  return array(
    'administer rtod integration' => array(
      'title' => 'Administer RTOD ingration',
      'description' => 'Allows to configurate RTOD integration process',
    ),
  );
}

/**
 * Implements hook_cron().
 */
function rtod_cron() {
  // Skip if regular procedure switched off in settings form.
  if (!variable_get('rtod_update_on_cron', 0)) return;

  $period = variable_get('rtod_update_period', 86400);
  $last_update = variable_get('rtod_lastupdate', 0);

  // Do work if 90% of period last.
  // Do not update since 00:00 till 02:59
  if (time() - $last_update > $period * 0.9 && date('G') > 2) {
    try {
      // Moscow
      $passportParser = new Drupal\rtod\PassportParser();
      $passportParser->actualizeAll();
      // Moscow region
      $passportParser = new Drupal\rtod\PassportParser('http://opendata.russiatourism.ru/7708550300-ReestrRosturizm50B');
      $passportParser->actualizeAll();
      variable_set('rtod_lastupdate', time());
    }
    catch (Exception $e) {
      watchdog('rtod', '%s', array('%s' => $e->getMessage()), WATCHDOG_ERROR);
    }
  }
}