<?php

// This file contains the current being tracked configurations.

$tracked = array (
  'field.field_collection_item.field_fs_date_signed.field_financial_supply' => '92f055e2a38b6aed001eb26fd761ec583e5c0d9f',
  'field.field_collection_item.field_fs_doc_number.field_financial_supply' => '0a13f590d21219a206cf495880a2104af8bf28aa',
  'field.field_collection_item.field_fs_org_fact_addr.field_financial_supply' => '2040c3f31d65968a7d27e803987172ce83b0dde1',
  'field.field_collection_item.field_fs_org_name.field_financial_supply' => 'fd5bc151efd715af4b48e0306142a2e221980544',
  'field.field_collection_item.field_fs_org_post_addr.field_financial_supply' => 'd17393f09dd76978a871ba09b2ce5ba33f5a5882',
  'field.field_collection_item.field_fs_period.field_financial_supply' => '45afa300fd37cf370e678b61ef4a1608512c63b0',
  'field.field_collection_item.field_fs_size.field_financial_supply' => 'bba535ec2b3e24ec6ce403d9bf768c4fb875d822',
  'field.field_collection_item.field_fs_type.field_financial_supply' => 'cd1e54b24d06630844aa1567e46a0ae8ddfa2db8',
  'field.taxonomy_term.field_financial_supply.tour_operators' => '59064d4f911bd87b72e18cea7c51096e3c750b01',
  'vocabulary.tour_operators' => '1ca93121902b83dc65a73a6bd1ab1c1ffead88e1',
  'ds_layout_settings.taxonomy_term|tour_operators|form' => '793b2466ec52876e657d62db01240e9261177c74',
);


// The following modules are required to run the configurations of this file.

$modules = array(
  'ctools',
  'ds',
  'field_sql_storage',
  'date',
  'text',
  'number',
  'field_collection',
  'taxonomy',
);
