<?php

// This file contains the current being tracked configurations.

$tracked = array (
  'field.field_collection_item.field_fs_date_signed.field_financial_supply' => 'b1a06696e08101af8af330611bb341f459aa15cf',
  'field.field_collection_item.field_fs_doc_number.field_financial_supply' => 'ce54c55b8b755086af1d1cb43ff426235cbb85fb',
  'field.field_collection_item.field_fs_org_fact_addr.field_financial_supply' => 'aed6292e83168c6595cdd35ea6cc29750ded28b3',
  'field.field_collection_item.field_fs_org_name.field_financial_supply' => '837fa91d6b02ce19e0d96a79c5d0eccdddee6e99',
  'field.field_collection_item.field_fs_org_post_addr.field_financial_supply' => '874322cccea45b914052f669689f233d3f7aa3d3',
  'field.field_collection_item.field_fs_period.field_financial_supply' => '314208ac26ee4de62d490bb9f86b40794e2a206f',
  'field.field_collection_item.field_fs_size.field_financial_supply' => 'c24bcf6b90f8b438b0a6b0545a27ad8f9e70ff76',
  'field.field_collection_item.field_fs_type.field_financial_supply' => '105479882b1b55757cd20127280def5df1e4b12a',
  'field.taxonomy_term.field_financial_supply.tour_operators' => 'dffeb5295cd7c0631e3769a327087cc7e611bfe2',
  'permission.choose_taxonomy_term_revisions' => 'cf8ea1d6f621d9f2ce4af6a89191b2cdb4d263ed',
  'permission.delete_taxonomy_term_revisions' => '78552772aa0ef02a426d02794ff4eed934b49159',
  'permission.revert_taxonomy_term_revisions' => 'd43f9847ddc23f55fd243c387bdb8b25078f5f55',
  'permission.view_taxonomy_term_revisions' => '94e92d8d46ecce47e9c84ffb431da01df52b0947',
  'vocabulary.tour_operators' => '1ca93121902b83dc65a73a6bd1ab1c1ffead88e1',
  'ds_layout_settings.taxonomy_term|tour_operators|form' => '793b2466ec52876e657d62db01240e9261177c74',
);


// The following modules are required to run the configurations of this file.

$modules = array(
  'ctools',
  'ds',
  'field_sql_storage',
  'date',
  'text',
  'number',
  'field_collection',
  'taxonomy_revision',
  'taxonomy',
);
